[project]
name = "baligh"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "camel-tools>=1.5.7",
    "farasapy>=0.1.1",
    "pydantic>=2.13.4",
    "pyarabic",
    "torch>=2.4",
    "arramooz-pysqlite",
    "sparqlwrapper",
    "pyyaml>=6.0",
    "loguru>=0.7.3",
    "marisa-trie>=1.2.1",
    "joblib>=1.5.0",
    "scikit-learn>=1.7.0",
    "sklearn-crfsuite>=0.5.0",
    "msgpack>=1.1.0",
    "sentencepiece>=0.2.0",
    "transformers>=4.43.4",
    "accelerate>=0.21.0",
    "pytorch-crf>=0.1.0"
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "motor>=3.6.0",
    "python-dotenv>=1.0.0",
    "pydantic-settings>=2.0.0",
]

[dependency-groups]
dev = [
  "pre-commit>=4.2.0",
  "ruff>=0.11.0",
  "mypy>=1.15.0",
  "pytest>=8.3.5",
  "ipykernel>=7.2.0",
  "pandas>=2.3.0",
  "types-PyYAML>=6.0",
  "datasets>=3.2.0",
]

[tool.ruff]
target-version = "py311"
src = ["src", "tests"]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "D"]
ignore = ["D", "E402", "E501", "B905", "B007"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.12"
files = ["src", "tests"]
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = [
    "camel_tools.*",
    "torchcrf.*",
    "farasa.*",
    "joblib",
    "marisa_trie",
    "pyarabic.*",
    "sklearn_crfsuite.*",
    "tqdm.*",
    "datasets.*",
    "sentencepiece.*",
    "msgpack.*",
    "onnxruntime.*",
    "arramooz.*",
    "transformers.*"
]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
