[project]
name = "baligh"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "camel-tools>=1.5.7",
    "farasapy>=0.1.1",
    "pydantic>=2.13.4",
    "torch<2.3",
    "arramooz-pysqlite",
    "sparqlwrapper",
]

[dependency-groups]
dev = [
  "pre-commit>=4.2.0",
  "ruff>=0.11.0",
  "mypy>=1.15.0",
  "pytest>=8.3.5",
  "pytest-asyncio",
  "ipykernel>=7.2.0",
]

[tool.ruff]
target-version = "py311"
src = ["src", "tests"]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "D"]
ignore = ["D203", "D211", "D213"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.11"
files = ["src", "tests"]

[[tool.mypy.overrides]]
module = [
    "camel_tools.*",
    "farasa.*",
    "arramooz.*"
]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

