"""Evaluation utilities for the GEC edit tagger."""

import json
import torch
import numpy as np
from collections import Counter
from tqdm import tqdm

def _load_test_raw(test_jsonl_path: str) -> list[dict]:
    """Load the raw test JSONL file.
    Args:
        test_jsonl_path: Path to the JSONL file generated by the feature
            pipeline.
    Returns:
        List of dictionaries, each containing ``subwords`` and label
        information.
    """
    with open(test_jsonl_path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]

def evaluate_model(model, test_loader, device):
    """Run inference on the test set and collect predictions.

    Args:
        model: The (optionally CRF‑wrapped) model.
        test_loader: ``torch.utils.data.DataLoader`` yielding batches.
        device: Torch device string or object.
    Returns:
        Tuple ``(all_preds, all_labels)`` where each is a ``np.ndarray`` of shape
        ``(num_examples, seq_len)``.
    """
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for batch in tqdm(test_loader, desc="Evaluating"):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"]

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            # The model may return either raw logits (standard) or decoded ids (CRF)
            if isinstance(outputs, dict) and "logits" in outputs:
                logits = outputs["logits"]
            else:
                logits = outputs.logits

            if logits.dim() == 3:
                # Standard model – take argmax over label dimension
                pred_ids = logits.argmax(dim=-1).cpu().numpy()
            else:
                # CRF model – logits already contain decoded label ids
                pred_ids = logits.cpu().numpy()

            all_preds.append(pred_ids)
            all_labels.append(labels.numpy())

    all_preds = np.concatenate(all_preds, axis=0)
    all_labels = np.concatenate(all_labels, axis=0)
    return all_preds, all_labels

def compute_overall_metrics(all_preds, all_labels, ignore_index=-100):
    """Print overall token level metrics.

    Returns a dict for programmatic use. Also prints a formatted table.
    """
    mask = all_labels != ignore_index
    filtered_preds = all_preds[mask]
    filtered_labels = all_labels[mask]

    correct = int((filtered_preds == filtered_labels).sum())
    total = len(filtered_labels)
    accuracy = correct / total if total > 0 else 0.0

    tp = fp = fn = 0
    for pred, gold in zip(filtered_preds.tolist(), filtered_labels.tolist()):
        if pred == gold:
            tp += 1
        else:
            fp += 1
            fn += 1

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    beta_sq = 0.25
    f05 = (
        (1 + beta_sq) * precision * recall / (beta_sq * precision + recall)
        if (beta_sq * precision + recall) > 0
        else 0.0
    )

    print("=" * 50)
    print(f"{'Metric':<20} {'Value':>10}")
    print("-" * 50)
    print(f"{'Total tokens':<20} {total:>10}")
    print(f"{'Correct':<20} {correct:>10}")
    print(f"{'Accuracy':<20} {accuracy:>10.4f}")
    print(f"{'Precision':<20} {precision:>10.4f}")
    print(f"{'Recall':<20} {recall:>10.4f}")
    print(f"{'F0.5':<20} {f05:>10.4f}")
    print("=" * 50)

    return {
        "total": total,
        "correct": correct,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f05": f05,
    }


def compute_per_label_metrics(all_preds, all_labels, id2label, ignore_index=-100):
    """Compute per-label precision/recall/F0.5 and print top-50 by support.
    """
    mask = all_labels != ignore_index
    filtered_preds = all_preds[mask]
    filtered_labels = all_labels[mask]

    label_tp = Counter()
    label_fp = Counter()
    label_fn = Counter()
    label_support = Counter()

    for pred, gold in zip(filtered_preds.tolist(), filtered_labels.tolist()):
        gold_name = id2label.get(gold, "[UNKNOWN]")
        pred_name = id2label.get(pred, "[UNKNOWN]")
        label_support[gold_name] += 1
        if pred == gold:
            label_tp[gold_name] += 1
        else:
            label_fp[pred_name] += 1
            label_fn[gold_name] += 1

    rows = []
    beta_sq = 0.25
    for label in sorted(label_support, key=label_support.get, reverse=True):
        tp = label_tp[label]
        fp = label_fp.get(label, 0)
        fn = label_fn.get(label, 0)
        p = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        r = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f = (
            (1 + beta_sq) * p * r / (beta_sq * p + r)
            if (beta_sq * p + r) > 0
            else 0.0
        )
        rows.append((label, label_support[label], p, r, f))

    # Print header
    print("Label" + " " * 33 + "Support   Prec      Rec     F0.5")
    print("-" * 80)
    for label, support, p, r, f in rows[:50]:
        print(f"{label:<40} {support:>8} {p:>8.4f} {r:>8.4f} {f:>8.4f}")
    if len(rows) > 50:
        print(f"\n... and {len(rows) - 50} more labels")

    return rows


def _label_to_op(label_name: str) -> str:
    """Map a label token to its operation type (KEEP/REPLACE/INSERT/DELETE/OTHER)."""
    if label_name.startswith("K") or label_name.startswith("[PAD") or label_name.startswith("[UNK"):
        return "KEEP"
    if label_name.startswith("R_"):
        return "REPLACE"
    if label_name.startswith("I_"):
        return "INSERT"
    if label_name.startswith("D"):
        return "DELETE"
    return "OTHER"


def compute_operation_metrics(all_preds, all_labels, id2label, ignore_index=-100):
    """Aggregate metrics by operation type (K, R, I, D, OTHER)."""
    mask = all_labels != ignore_index
    filtered_preds = all_preds[mask]
    filtered_labels = all_labels[mask]

    op_tp = Counter()
    op_fp = Counter()
    op_fn = Counter()
    op_support = Counter()

    for pred, gold in zip(filtered_preds.tolist(), filtered_labels.tolist()):
        gold_name = id2label.get(gold, "[UNKNOWN]")
        pred_name = id2label.get(pred, "[UNKNOWN]")
        gold_op = _label_to_op(gold_name)
        pred_op = _label_to_op(pred_name)
        op_support[gold_op] += 1
        if gold_op == pred_op:
            op_tp[gold_op] += 1
        else:
            op_fp[pred_op] += 1
            op_fn[gold_op] += 1

    beta_sq = 0.25
    ops = ["KEEP", "REPLACE", "INSERT", "DELETE", "OTHER"]
    print(f"{'Operation':<12} {'Support':>8} {'Prec':>8} {'Rec':>8} {'F0.5':>8}")
    print("-" * 56)
    for op in ops:
        tp = op_tp.get(op, 0)
        fp = op_fp.get(op, 0)
        fn = op_fn.get(op, 0)
        p = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        r = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f = (
            (1 + beta_sq) * p * r / (beta_sq * p + r)
            if (beta_sq * p + r) > 0
            else 0.0
        )
        print(f"{op:<12} {op_support.get(op,0):>8} {p:>8.4f} {r:>8.4f} {f:>8.4f}")

    return {
        op: {"support": op_support.get(op, 0), "prec": p, "rec": r, "f05": f}
        for op in ops
    }


def print_sample_predictions(test_jsonl_path: str, all_preds: np.ndarray, id2label: dict, num_samples: int = 5):
    """Print a small set of sample predictions with mismatched tokens.

    Args:
        test_jsonl_path: Path to the test JSONL file.
        all_preds: Numpy array of predictions (same shape as labels).
        id2label: Mapping from label id to string.
        num_samples: Number of examples to display.
    """
    test_raw = _load_test_raw(test_jsonl_path)
    n_samples = min(num_samples, len(test_raw))
    for i in range(n_samples):
        subwords = test_raw[i]["subwords"]
        gold_labels = test_raw[i].get("labels_star", test_raw[i].get("labels", []))
        pred_ids_i = all_preds[i][: len(subwords)]
        pred_names = [id2label.get(pid, "[UNK]") for pid in pred_ids_i]

        print(f"\n--- Example {i+1} ---")
        mismatches = 0
        total_toks = 0
        for sw, gl, pl in zip(subwords, gold_labels, pred_names):
            if gl != pl:
                mismatches += 1
            total_toks += 1
        print(f"Token accuracy: {1 - mismatches/total_toks:.4f} ({total_toks - mismatches}/{total_toks})")
        print()
        print(f"{'Subword':<20} {'Gold':<30} {'Pred':<30} {'Match'}")
        print("-" * 80)
        for sw, gl, pl in zip(subwords, gold_labels, pred_names):
            mark = "OK" if gl == pl else "WRONG"
            if gl != pl:
                print(f"{sw:<20} {gl:<30} {pl:<30} {mark}")
        print("\n(Showing only mismatched tokens above)")
